export const SET_HERO = 'SET_HERO';
export const SET_IS_FETCHTING = 'SET_IS_FETCHTING';
export const SET_IS_ABOUT = 'SET_IS_ABOUT';
export const SET_ADD_FAVORITE = 'SET_ADD_FAVORITE';
export const REMOVE_FROM_FAVORITE = 'REMOVE_FROM_FAVORITE';
export const CLEAR_BUTTON = 'CLEAR_BUTTON';
